require 'rubygems'
require 'spec'
require 'lib/bounding_box'
require 'lib/segment'
require 'lib/node'
require 'lib/point'
require 'lib/trapezoid_node'
require 'lib/trapezoid'
require 'lib/trapezoidal_maps'
require 'lib/xnode'
require 'lib/ynode'
require 'lib/drawer'
require 'lib/graph'
require 'libglade2'

