/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_colordialog (void);
GtkWidget* create_opendialog (void);
GtkWidget* create_savedialog (void);
GtkWidget* create_aboutdialog (void);
