/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *menu_new;
  GtkWidget *menu_open;
  GtkWidget *menu_save;
  GtkWidget *menu_save_as;
  GtkWidget *separatormenuitem1;
  GtkWidget *menu_close;
  GtkWidget *menuitem6;
  GtkWidget *menuitem6_menu;
  GtkWidget *show_trapezoids;
  GtkWidget *show_graph;
  GtkWidget *robot_line;
  GtkWidget *separador1;
  GtkWidget *colors;
  GtkWidget *colors_menu;
  GtkWidget *colors_graph;
  GtkWidget *color_trapezoids;
  GtkWidget *trapezoids_segments;
  GtkWidget *new_trapezoides;
  GtkWidget *destroied_trapezoids;
  GtkWidget *color_segments;
  GtkWidget *color_robot;
  GtkWidget *robot_line_color;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *toolbar_new;
  GtkWidget *toolbar_open;
  GtkWidget *toolbar_save;
  GtkWidget *separatortoolitem2;
  GtkWidget *tmp_image;
  GtkWidget *toolbar_record_points;
  GtkWidget *toolbar_generate_map;
  GtkWidget *toolbar_move;
  GtkWidget *toolbar_next_step;
  GtkWidget *separatortoolitem3;
  GtkWidget *toolitem1;
  GtkWidget *label4;
  GtkWidget *toolitem2;
  GtkObject *xvalue_adj;
  GtkWidget *xvalue;
  GtkWidget *toolitem3;
  GtkWidget *label5;
  GtkWidget *toolitem4;
  GtkObject *yvalue_adj;
  GtkWidget *yvalue;
  GtkWidget *add_point;
  GtkWidget *vbox2;
  GtkWidget *eventbox;
  GtkWidget *drawingarea;
  GtkWidget *hseparator1;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *speedscale;
  GtkWidget *stepbystep;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mainwindow, 800, 600);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("RobotPlanning"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Arquivo"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  menu_new = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (menu_new);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), menu_new);

  menu_open = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (menu_open);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), menu_open);

  menu_save = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (menu_save);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), menu_save);

  menu_save_as = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (menu_save_as);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), menu_save_as);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  menu_close = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (menu_close);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), menu_close);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("E_xibir"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menuitem6_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menuitem6_menu);

  show_trapezoids = gtk_check_menu_item_new_with_mnemonic (_("Trapezoides"));
  gtk_widget_show (show_trapezoids);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), show_trapezoids);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (show_trapezoids), TRUE);

  show_graph = gtk_check_menu_item_new_with_mnemonic (_("Grafo"));
  gtk_widget_show (show_graph);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), show_graph);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (show_graph), TRUE);

  robot_line = gtk_check_menu_item_new_with_mnemonic (_("Rastro"));
  gtk_widget_show (robot_line);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), robot_line);
  gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (robot_line), TRUE);

  separador1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separador1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), separador1);
  gtk_widget_set_sensitive (separador1, FALSE);

  colors = gtk_menu_item_new_with_mnemonic (_("Cores"));
  gtk_widget_show (colors);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), colors);

  colors_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (colors), colors_menu);

  colors_graph = gtk_menu_item_new_with_mnemonic (_("Grafo"));
  gtk_widget_show (colors_graph);
  gtk_container_add (GTK_CONTAINER (colors_menu), colors_graph);

  color_trapezoids = gtk_menu_item_new_with_mnemonic (_("Trapezoides - Fundo"));
  gtk_widget_show (color_trapezoids);
  gtk_container_add (GTK_CONTAINER (colors_menu), color_trapezoids);

  trapezoids_segments = gtk_menu_item_new_with_mnemonic (_("Trapezoides - Linha"));
  gtk_widget_show (trapezoids_segments);
  gtk_container_add (GTK_CONTAINER (colors_menu), trapezoids_segments);

  new_trapezoides = gtk_menu_item_new_with_mnemonic (_("Novos Trapezoides"));
  gtk_widget_show (new_trapezoides);
  gtk_container_add (GTK_CONTAINER (colors_menu), new_trapezoides);

  destroied_trapezoids = gtk_menu_item_new_with_mnemonic (_("Trapezoides Destru\303\255dos"));
  gtk_widget_show (destroied_trapezoids);
  gtk_container_add (GTK_CONTAINER (colors_menu), destroied_trapezoids);

  color_segments = gtk_menu_item_new_with_mnemonic (_("Segmentos"));
  gtk_widget_show (color_segments);
  gtk_container_add (GTK_CONTAINER (colors_menu), color_segments);

  color_robot = gtk_menu_item_new_with_mnemonic (_("Rob\303\264"));
  gtk_widget_show (color_robot);
  gtk_container_add (GTK_CONTAINER (colors_menu), color_robot);

  robot_line_color = gtk_menu_item_new_with_mnemonic (_("Rastro"));
  gtk_widget_show (robot_line_color);
  gtk_container_add (GTK_CONTAINER (colors_menu), robot_line_color);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("Aj_uda"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about = gtk_menu_item_new_with_mnemonic (_("_Sobre"));
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  toolbar_new = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-new");
  gtk_widget_show (toolbar_new);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_new);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_new), tooltips, _("Novo"), NULL);

  toolbar_open = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-open");
  gtk_widget_show (toolbar_open);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_open);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_open), tooltips, _("Abrir"), NULL);

  toolbar_save = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-save");
  gtk_widget_show (toolbar_save);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_save), tooltips, _("Salvar"), NULL);

  separatortoolitem2 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem2);

  toolbar_record_points = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbar_record_points), _("Adicionar Pontos"));
  tmp_image = gtk_image_new_from_stock ("gtk-media-record", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbar_record_points), tmp_image);
  gtk_widget_show (toolbar_record_points);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_record_points);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbar_record_points), tooltips, _("Adicionar Pontos"), NULL);

  toolbar_generate_map = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbar_generate_map), _("Gerar Trapezoides"));
  tmp_image = gtk_image_new_from_stock ("gtk-select-color", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbar_generate_map), tmp_image);
  gtk_widget_show (toolbar_generate_map);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_generate_map);

  toolbar_move = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toolbar_move), "");
  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  gtk_tool_button_set_icon_widget (GTK_TOOL_BUTTON (toolbar_move), tmp_image);
  gtk_widget_show (toolbar_move);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_move);

  tmp_image = gtk_image_new_from_stock ("gtk-media-forward", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbar_next_step = (GtkWidget*) gtk_tool_button_new (tmp_image, "");
  gtk_widget_show (toolbar_next_step);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolbar_next_step);

  separatortoolitem3 = (GtkWidget*) gtk_separator_tool_item_new ();
  gtk_widget_show (separatortoolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), separatortoolitem3);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  label4 = gtk_label_new (_("X: "));
  gtk_widget_show (label4);
  gtk_container_add (GTK_CONTAINER (toolitem1), label4);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem2);

  xvalue_adj = gtk_adjustment_new (1, 1, 799, 1, 10, 0);
  xvalue = gtk_spin_button_new (GTK_ADJUSTMENT (xvalue_adj), 1, 0);
  gtk_widget_show (xvalue);
  gtk_container_add (GTK_CONTAINER (toolitem2), xvalue);

  toolitem3 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem3);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem3);

  label5 = gtk_label_new (_("Y: "));
  gtk_widget_show (label5);
  gtk_container_add (GTK_CONTAINER (toolitem3), label5);

  toolitem4 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem4);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem4);

  yvalue_adj = gtk_adjustment_new (1, 1, 438, 1, 10, 0);
  yvalue = gtk_spin_button_new (GTK_ADJUSTMENT (yvalue_adj), 1, 0);
  gtk_widget_show (yvalue);
  gtk_container_add (GTK_CONTAINER (toolitem4), yvalue);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  add_point = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Adicionar"));
  gtk_widget_show (add_point);
  gtk_container_add (GTK_CONTAINER (toolbar1), add_point);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  eventbox = gtk_event_box_new ();
  gtk_widget_show (eventbox);
  gtk_box_pack_start (GTK_BOX (vbox2), eventbox, TRUE, TRUE, 0);

  drawingarea = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea);
  gtk_container_add (GTK_CONTAINER (eventbox), drawingarea);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator1, FALSE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  label1 = gtk_label_new (_("Velocidade: "));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  speedscale = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (100, 1, 100, 1, 10, 0)));
  gtk_widget_show (speedscale);
  gtk_box_pack_start (GTK_BOX (hbox1), speedscale, TRUE, TRUE, 0);
  gtk_scale_set_draw_value (GTK_SCALE (speedscale), FALSE);
  gtk_range_set_update_policy (GTK_RANGE (speedscale), GTK_UPDATE_DISCONTINUOUS);
  gtk_range_set_inverted (GTK_RANGE (speedscale), TRUE);

  stepbystep = gtk_check_button_new_with_mnemonic (_("Passo a Passo"));
  gtk_widget_show (stepbystep);
  gtk_box_pack_start (GTK_BOX (hbox1), stepbystep, FALSE, FALSE, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) menu_new, "activate",
                    G_CALLBACK (on_menu_new_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_open, "activate",
                    G_CALLBACK (on_menu_open_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_save, "activate",
                    G_CALLBACK (on_menu_save_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_save_as, "activate",
                    G_CALLBACK (on_menu_save_as_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_close, "activate",
                    G_CALLBACK (on_menu_close_activate),
                    NULL);
  g_signal_connect ((gpointer) show_trapezoids, "activate",
                    G_CALLBACK (on_show_trapezoids_activate),
                    NULL);
  g_signal_connect ((gpointer) show_graph, "activate",
                    G_CALLBACK (on_show_graph_activate),
                    NULL);
  g_signal_connect ((gpointer) robot_line, "activate",
                    G_CALLBACK (on_robot_line_activate),
                    NULL);
  g_signal_connect ((gpointer) colors_graph, "activate",
                    G_CALLBACK (on_colors_graph_activate),
                    NULL);
  g_signal_connect ((gpointer) color_trapezoids, "activate",
                    G_CALLBACK (on_color_trapezoids_activate),
                    NULL);
  g_signal_connect ((gpointer) trapezoids_segments, "activate",
                    G_CALLBACK (on_trapezoids_segments_activate),
                    NULL);
  g_signal_connect ((gpointer) new_trapezoides, "activate",
                    G_CALLBACK (on_new_trapezoides_activate),
                    NULL);
  g_signal_connect ((gpointer) destroied_trapezoids, "activate",
                    G_CALLBACK (on_destroied_trapezoids_activate),
                    NULL);
  g_signal_connect ((gpointer) color_segments, "activate",
                    G_CALLBACK (on_color_segments_activate),
                    NULL);
  g_signal_connect ((gpointer) color_robot, "activate",
                    G_CALLBACK (on_color_robot_activate),
                    NULL);
  g_signal_connect ((gpointer) robot_line_color, "activate",
                    G_CALLBACK (on_robot_line_color_activate),
                    NULL);
  g_signal_connect ((gpointer) about, "activate",
                    G_CALLBACK (on_about_activate),
                    NULL);
  g_signal_connect ((gpointer) toolbar_new, "clicked",
                    G_CALLBACK (on_toolbar_new_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbar_open, "clicked",
                    G_CALLBACK (on_toolbar_open_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbar_save, "clicked",
                    G_CALLBACK (on_toolbar_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) toolbar_record_points, "toggled",
                    G_CALLBACK (on_toolbar_record_poits_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbar_generate_map, "toggled",
                    G_CALLBACK (on_toolbar_generate_map_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbar_move, "toggled",
                    G_CALLBACK (on_toolbar_move_toggled),
                    NULL);
  g_signal_connect ((gpointer) toolbar_next_step, "clicked",
                    G_CALLBACK (on_toolbar_next_step_clicked),
                    NULL);
  g_signal_connect ((gpointer) add_point, "clicked",
                    G_CALLBACK (on_add_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) speedscale, "value_changed",
                    G_CALLBACK (on_speedscale_value_changed),
                    NULL);
  g_signal_connect ((gpointer) stepbystep, "toggled",
                    G_CALLBACK (on_stepbystep_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, menu_new, "menu_new");
  GLADE_HOOKUP_OBJECT (mainwindow, menu_open, "menu_open");
  GLADE_HOOKUP_OBJECT (mainwindow, menu_save, "menu_save");
  GLADE_HOOKUP_OBJECT (mainwindow, menu_save_as, "menu_save_as");
  GLADE_HOOKUP_OBJECT (mainwindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, menu_close, "menu_close");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem6_menu, "menuitem6_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, show_trapezoids, "show_trapezoids");
  GLADE_HOOKUP_OBJECT (mainwindow, show_graph, "show_graph");
  GLADE_HOOKUP_OBJECT (mainwindow, robot_line, "robot_line");
  GLADE_HOOKUP_OBJECT (mainwindow, separador1, "separador1");
  GLADE_HOOKUP_OBJECT (mainwindow, colors, "colors");
  GLADE_HOOKUP_OBJECT (mainwindow, colors_menu, "colors_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, colors_graph, "colors_graph");
  GLADE_HOOKUP_OBJECT (mainwindow, color_trapezoids, "color_trapezoids");
  GLADE_HOOKUP_OBJECT (mainwindow, trapezoids_segments, "trapezoids_segments");
  GLADE_HOOKUP_OBJECT (mainwindow, new_trapezoides, "new_trapezoides");
  GLADE_HOOKUP_OBJECT (mainwindow, destroied_trapezoids, "destroied_trapezoids");
  GLADE_HOOKUP_OBJECT (mainwindow, color_segments, "color_segments");
  GLADE_HOOKUP_OBJECT (mainwindow, color_robot, "color_robot");
  GLADE_HOOKUP_OBJECT (mainwindow, robot_line_color, "robot_line_color");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (mainwindow, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (mainwindow, about, "about");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_new, "toolbar_new");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_open, "toolbar_open");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_save, "toolbar_save");
  GLADE_HOOKUP_OBJECT (mainwindow, separatortoolitem2, "separatortoolitem2");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_record_points, "toolbar_record_points");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_generate_map, "toolbar_generate_map");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_move, "toolbar_move");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar_next_step, "toolbar_next_step");
  GLADE_HOOKUP_OBJECT (mainwindow, separatortoolitem3, "separatortoolitem3");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (mainwindow, xvalue, "xvalue");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem3, "toolitem3");
  GLADE_HOOKUP_OBJECT (mainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem4, "toolitem4");
  GLADE_HOOKUP_OBJECT (mainwindow, yvalue, "yvalue");
  GLADE_HOOKUP_OBJECT (mainwindow, add_point, "add_point");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainwindow, eventbox, "eventbox");
  GLADE_HOOKUP_OBJECT (mainwindow, drawingarea, "drawingarea");
  GLADE_HOOKUP_OBJECT (mainwindow, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, label1, "label1");
  GLADE_HOOKUP_OBJECT (mainwindow, speedscale, "speedscale");
  GLADE_HOOKUP_OBJECT (mainwindow, stepbystep, "stepbystep");
  GLADE_HOOKUP_OBJECT (mainwindow, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (mainwindow), accel_group);

  return mainwindow;
}

